# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.random.randint(10, size=6)

print('list(a):', list(a))
print('a.tolist():', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b):', list(b))
print('b.tolist():', b.tolist())

list(a): [1, 3, 7, 1, 8, 7]
a.tolist(): [1, 3, 7, 1, 8, 7]
list(b): [array([8, 5]), array([4, 0]), array([6, 3])]
b.tolist(): [[8, 5], [4, 0], [6, 3]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件

import numpy as np
a = np.random.randint(10, size=6)

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[5 2 8 3 6 5]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3, 4))

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[1 0 8 3]
 [1 7 9 5]
 [0 6 6 8]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [7]:
c = np.random.randint(10, size=(2, 3, 10))

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[5 8 7 6 2 7 6 7 6 6]
  [6 9 3 9 3 0 2 2 5 5]
  [6 5 7 6 7 7 5 4 9 4]]

 [[3 4 0 5 3 5 9 3 1 4]
  [7 0 6 2 6 5 4 4 6 0]
  [1 8 7 1 5 3 6 2 2 9]]]
3
(2, 3, 10)
60
int32
4
2
<class 'numpy.ndarray'>


In [8]:
c

array([[[5, 8, 7, 6, 2, 7, 6, 7, 6, 6],
        [6, 9, 3, 9, 3, 0, 2, 2, 5, 5],
        [6, 5, 7, 6, 7, 7, 5, 4, 9, 4]],

       [[3, 4, 0, 5, 3, 5, 9, 3, 1, 4],
        [7, 0, 6, 2, 6, 5, 4, 4, 6, 0],
        [1, 8, 7, 1, 5, 3, 6, 2, 2, 9]]])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 8, 8, 1, 0, 8]
[6, 8, 8, 1, 0, 8]


In [10]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 3, 6, 3], [0, 0, 0, 9], [2, 6, 8, 3]]
[array([9, 3, 6, 3]), array([0, 0, 0, 9]), array([2, 6, 8, 3])]


In [11]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 9], [9, 2], [4, 5]], [[3, 7], [4, 3], [4, 0]]]
[array([[7, 9],
       [9, 2],
       [4, 5]]), array([[3, 7],
       [4, 3],
       [4, 0]])]


In [12]:
def tolist(interable):
    if type(interable) != np.ndarray:
        return interable
    newlist = []
    for obj in interable:
        newlist.append(tolist(obj))
    return list(newlist)
   
print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 8, 1, 0, 8]
[[9, 3, 6, 3], [0, 0, 0, 9], [2, 6, 8, 3]]
[[[7, 9], [9, 2], [4, 5]], [[3, 7], [4, 3], [4, 0]]]


In [20]:
def tolist_test(interable):
    for obj in interable:
        for objj in obj:
            print(objj)
            print(type(objj))
            print('***')

In [21]:
print(tolist_test(c))

[7 9]
<class 'numpy.ndarray'>
***
[9 2]
<class 'numpy.ndarray'>
***
[4 5]
<class 'numpy.ndarray'>
***
[3 7]
<class 'numpy.ndarray'>
***
[4 3]
<class 'numpy.ndarray'>
***
[4 0]
<class 'numpy.ndarray'>
***
None


In [15]:
c

array([[[7, 9],
        [9, 2],
        [4, 5]],

       [[3, 7],
        [4, 3],
        [4, 0]]])